CREATE TABLE IF NOT EXISTS categories (
    L3_product_category_code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    L3_product_category_name VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS chains (
    chain_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_name VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS customers (
    CH3_ship_to_code INT AS IDENTITY PRIMARY KEY,
    CH3_ship_to_name VARCHAR(255),
    chains INT REFERENCES chains(chain_id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS products (
    material_no INT AS IDENTITY PRIMARY KEY,
    material_desc_rus VARCHAR(255),
    category INT REFERENCES categories(L3_product_category_code) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS prices (
    price_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chains INT REFERENCES chains(chain_id) ON DELETE CASCADE,
    product_material_no INT REFERENCES products(material_no) ON DELETE CASCADE,
    regular_price_per_unit FLOAT
    );

CREATE TABLE IF NOT EXISTS actuals (
    actual_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dates DATE(255),
    specification_description VARCHAR(255)
    );
