CREATE TABLE IF NOT EXISTS categories (
    product_category_code INT PRIMARY KEY,
    product_category_name VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS chains (
    chain_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_name VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS customers (
    ship_to_code INT PRIMARY KEY,
    ship_to_name VARCHAR(255),
    chains INT REFERENCES chains(chain_id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS products (
    material_no INT PRIMARY KEY,
    material_desc_rus VARCHAR(1000),
    category INT REFERENCES categories(product_category_code) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS prices (
    price_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chains INT REFERENCES chains(chain_id) ON DELETE CASCADE,
    product_material_no INT REFERENCES products(material_no) ON DELETE CASCADE,
    regular_price_per_unit FLOAT
    );

CREATE TABLE IF NOT EXISTS actuals (
    actual_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dates TIMESTAMP WITHOUT TIME ZONE,
    product_material_no INT REFERENCES products(material_no) ON DELETE CASCADE,
    customer INT REFERENCES customers(ship_to_code) ON DELETE CASCADE,
    chains INT REFERENCES chains(chain_id) ON DELETE CASCADE,
    volume_units INT,
    actual_sales_value FLOAT,
    promo_sign VARCHAR(255)
    );
